# Generated by Django 3.1.6 on 2021-02-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210219_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDIImage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image'),
        ),
    ]
