# Generated by Django 3.1.6 on 2021-02-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_prdiimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDIImage',
            new_name='PRDImage',
        ),
    ]
